module.exports = {
  extends: [
    'stylelint-config-prettier',
    'stylelint-config-standard',
    'stylelint-config-recommended',
    'stylelint-config-recommended-scss',
    'stylelint-config-css-modules',
  ],
  plugins: [
    'stylelint-scss',
    'stylelint-selector-bem-pattern',
    'stylelint-order',
    'stylelint-declaration-block-no-ignored-properties',
  ],
  rules: {
    'declaration-colon-space-after': 'always',
    'declaration-colon-space-before': 'never',
    'block-opening-brace-space-before': 'always',
    'block-closing-brace-empty-line-before': 'never',
    'declaration-empty-line-before': [
      'never',
      {
        ignore: ['after-declaration'],
      },
    ],
    'declaration-block-single-line-max-declarations': 1,
    'comment-empty-line-before': [
      'always',
      {
        ignore: ['stylelint-commands', 'after-comment'],
      },
    ],
    'at-rule-blacklist': ['extend', 'debug'],
    'at-rule-no-vendor-prefix': true,
    'max-nesting-depth': 3,
    'declaration-no-important': true,
    'no-duplicate-selectors': true,
    'block-no-empty': true,
    'at-rule-empty-line-before': [
      'always',
      {
        except: ['first-nested'],
        ignoreAtRules: ['import'],
      },
    ],
    'at-rule-name-case': 'lower',
    'color-hex-case': 'lower',
    'color-hex-length': 'short',
    'color-no-invalid-hex': true,
    'color-named': 'never',
    'comment-no-empty': true,
    'comment-whitespace-inside': 'always',
    'declaration-bang-space-after': 'never',
    'declaration-bang-space-before': 'always',
    'declaration-block-semicolon-newline-after': 'always',
    'declaration-block-semicolon-space-before': 'never',
    'declaration-block-trailing-semicolon': 'always',
    'declaration-block-no-duplicate-properties': true,
    'declaration-property-value-blacklist': {
      '/^border/': ['none'],
    },
    'font-family-no-missing-generic-family-keyword': true,
    'function-comma-space-after': 'always-single-line',
    'function-parentheses-space-inside': 'never-single-line',
    'function-comma-space-before': 'never',
    'function-url-quotes': 'always',
    indentation: [2],
    'length-zero-no-unit': true,
    'max-empty-lines': 1,
    'media-feature-name-no-vendor-prefix': true,
    'media-feature-parentheses-space-inside': 'never',
    'no-missing-end-of-source-newline': true,
    'number-leading-zero': 'always',
    'number-no-trailing-zeros': true,
    'property-no-unknown': true,
    'property-no-vendor-prefix': true,
    'rule-empty-line-before': [
      'always',
      {
        ignore: ['after-comment'],
        except: ['first-nested'],
      },
    ],
    'selector-class-pattern': [
      '^[a-z0-9\\-]+$',
      {
        message:
          'Selector should be written in lowercase with hyphens (selector-class-pattern)',
      },
    ],
    'selector-list-comma-newline-after': 'always',
    'selector-max-compound-selectors': 3,
    'selector-max-id': 0,
    'selector-no-qualifying-type': true,
    'selector-no-vendor-prefix': true,
    'selector-pseudo-element-colon-notation': 'double',
    'selector-pseudo-element-no-unknown': true,
    'shorthand-property-no-redundant-values': true,
    'string-quotes': 'single',
    'value-no-vendor-prefix': true,
    'value-list-comma-space-after': 'always-single-line',
  },
};
